# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Bridge/Glide/Bundle/'
            - '../src/Stenope/Processor/ResizeImagesContentProcessor.php'
            - '../src/Stenope/Provider/SampleRemovalProvider.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Stenope\Processor\DefaultTocProcessor:
        tags:
            - name: 'stenope.processor'
              priority: '-90' # before the TableOfContentProcessor

    # Override default HTML Anchor processor:
    Stenope\Bundle\Processor\HtmlAnchorProcessor: '@App\Stenope\Processor\HtmlAnchorProcessor'
    App\Stenope\Processor\HtmlAnchorProcessor:
        tags: [{ name: stenope.processor, priority: -20 }]

    App\Stenope\Processor\GithubEditLinkProcessor:
        $repository: '%env(APP_GITHUB_REPO)%'
        $reference: '%env(APP_GITHUB_REF)%'

    resize_images_content_processor.case_study:
        class: App\Stenope\Processor\ResizeImagesContentProcessor
        arguments:
            $type: App\Model\CaseStudy
            $preset: case_study_content

    resize_images_content_processor.article:
        class: App\Stenope\Processor\ResizeImagesContentProcessor
        arguments:
            $type: App\Model\Article
            $preset: article_content

    App\Stenope\Provider\SampleRemovalProvider.Article:
        class: App\Stenope\Provider\SampleRemovalProvider
        decorates: stenope.provider.files.App\Model\Article
        arguments:
            $provider: '@.inner'
            $disabled: '%env(bool:INCLUDE_SAMPLES)%'
            $ignored: ['styleguide/example']

    App\Stenope\Manager\FilteringArticlesContentManager:
        decorates: Stenope\Bundle\ContentManagerInterface
        arguments:
            $contentManager: '@.inner'
            $filterUnpublished: '%env(not:bool:SHOW_UNPUBLISHED_ARTICLES)%'

    App\Stenope\Provider\SampleRemovalProvider.CaseStudy:
        class: App\Stenope\Provider\SampleRemovalProvider
        decorates: stenope.provider.files.App\Model\CaseStudy
        arguments:
            $provider: '@.inner'
            $disabled: '%env(bool:INCLUDE_SAMPLES)%'
            $ignored: ['example']

    App\Stenope\Provider\SampleRemovalProvider.Job:
        class: App\Stenope\Provider\SampleRemovalProvider
        decorates: stenope.provider.files.App\Model\Job
        arguments:
            $provider: '@.inner'
            $disabled: '%env(bool:INCLUDE_SAMPLES)%'
            $ignored: ['example']

    App\Command\GenerateArticleCommand:
        arguments:
            $path: '%kernel.project_dir%/content/blog'
