twitter_like:
    # https://developer.twitter.com/en/docs/twitter-for-websites/web-intents/overview#like-a-tweet
    path: /intent/like

twitter_rix_tweet:
    path: /rix_fr/status/{tweetId}

twitter_account:
    path: /{account}
