name: rix

services:

    ##########
    # System #
    ##########

    system:
        hostname: rix
        build:
            context: ..
            dockerfile: docker/Dockerfile
        image: rix:20230226135948
        restart: always
        ports:
            - 8000:80
            - 8080:8080
        volumes:
            - ../..:${MANALA_DIR}
        environment:
            MANALA_DIR: ${MANALA_DIR}
            MANALA_CACHE_DIR: ${MANALA_CACHE_DIR}
        working_dir: ${MANALA_DIR}
