name: rix

services:

    ##########
    # System #
    ##########

    system:
        hostname: rix
        build:
            context: .
            target: system
        image: rix:20220823194924
        restart: always
        ports:
            - 8000:80
            - 8080:8080
        volumes:
            - ../..:${DIR}
        environment:
            DIR: ${DIR}
            CACHE_DIR: ${CACHE_DIR}
        working_dir: ${DIR}
        entrypoint: .manala/docker/entrypoint.sh
